### ISSUE TITLE
ValueError('month must be in 1..12')

### ISSUE THREAD

**Issue by RediskaWzik** [alryaz/hass-energosbyt-plus#5]
На версии HA 2022.2.1 (возможно, раньше) возникает такая ошибка.
`Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.energosbyt_plus._base
Source: custom_components/energosbyt_plus/api.py:605
Integration: Личный кабинет ЭнергосбыТ.Плюс (documentation, issues)
First occurred: 10:53:35 (3 occurrences)
Last logged: 10:53:36

Error occurred during task execution: ValueError('month must be in 1..12')
Traceback (most recent call last):
  File "/config/custom_components/energosbyt_plus/sensor.py", line 335, in _collective_get_meter_data_for_account
    collective_update_future = cls._collective_update_futures[account_id]
KeyError: 'UESB|**мой ЛС**'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/energosbyt_plus/_base.py", line 259, in _wrap_update_task
    return await update_task
  File "/config/custom_components/energosbyt_plus/sensor.py", line 368, in async_refresh_account
    meters, characteristics = await asyncio.gather(
  File "/config/custom_components/energosbyt_plus/sensor.py", line 340, in _collective_get_meter_data_for_account
    meters = await account.async_get_meters()
  File "/config/custom_components/energosbyt_plus/api.py", line 1045, in async_get_meters
    return await self.api.async_get_meters(self.id)
  File "/config/custom_components/energosbyt_plus/api.py", line 363, in async_get_meters
    return Meter.de_json_list(
  File "/config/custom_components/energosbyt_plus/api.py", line 441, in de_json_list
    return tuple(cls.de_json(item, api, **kwargs) for item in data)
  File "/config/custom_components/energosbyt_plus/api.py", line 441, in <genexpr>
    return tuple(cls.de_json(item, api, **kwargs) for item in data)
  File "/config/custom_components/energosbyt_plus/api.py", line 605, in de_json
    accepted_period = date(
ValueError: month must be in 1..12
`

**Comment by mvbl** [comment]
Проект заброшен, видимо.
